main: dev.buchstabet.prefixes.Prefixes
name: prefixes
version: 1.0
author: Buchstabet
api-version: 1.20

commands:
  color:
    permission: "prefixes.command.color"
    aliases:
      - colors
      - farbe